spring.application.name=mcp-server
server.port=8082

# NOTE: We must disable the banner and the console logging
# to allow the STDIO transport to work !!!
# In this example, we are using WebMVC Server Transport
#spring.main.banner-mode=off
#logging.file.name=./logs/spring-boot-ai-mcp-server.log

# NOTE: important, we must uncomment the property below
# for using in Claude Ai like Client
# and stdio
#logging.pattern.console=
# This is not needed for WebMVC but for stdio
#spring.main.web-application-type=none

spring.ai.mcp.server.name=mcp-server
spring.ai.mcp.server.type=sync
spring.ai.mcp.server.sse-endpoint=/sse
spring.ai.mcp.server.sse-message-endpoint=/mcp/message
spring.ai.mcp.server.version=0.0.1

# Postgres connection properties
spring.datasource.url= jdbc:postgresql://localhost:5432/chat_app
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username= postgres
spring.datasource.password= admin